name: arcadia_account_manager_workspace
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/account_core
  - packages/account_store
  - packages/wisa_api
  - packages/smartschool_api
  - packages/azure_api
  - packages/account_linker
  - packages/account_actions

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.0
  coverage: ^1.9.0
